export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REQUESTING = "REQUESTING";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const OPENED_MODALS = "OPENED_MODALS";